swc() rule breaks copying files after first build
swc() rule that compiles transitive dependencies succeeds
on first build, but fails on second build while copying
files.

```
$ cd js && npm install && bazel clean --expunge && bazel build //:swc && bazel build //:swc
npm WARN bazel-swc-test@0.0.1 No description
npm WARN bazel-swc-test@0.0.1 No repository field.

added 14 packages from 66 contributors and audited 14 packages in 1.092s
found 0 vulnerabilities

INFO: Starting clean.
Starting local Bazel server and connecting to it...
INFO: Analyzed target //:swc (68 packages loaded, 403 targets configured).
INFO: Found 1 target...
Target //:swc up-to-date:
  bazel-bin/node_modules/aws-sdk/scripts/services-table-generator.js
INFO: Elapsed time: 10.869s, Critical Path: 0.83s
INFO: 60 processes: 33 internal, 1 darwin-sandbox, 26 local.
INFO: Build completed successfully, 60 total actions
INFO: Analyzed target //:swc (1 packages loaded, 25 targets configured).
INFO: Found 1 target...
ERROR: /path/to/bazel-sandbox/js/BUILD.bazel:3:4: Copying file bazel-bin/node_modules/aws-sdk/scripts/services-table-generator.ts failed: (Exit 1): bash failed: error executing command /bin/bash -c 'cp -f "$1" "$2"' '' bazel-bin/node_modules/aws-sdk/scripts/services-table-generator.ts bazel-out/darwin-fastbuild/bin/bazel-bin/node_modules/aws-sdk/scripts/services-table-generator.ts
cp: bazel-bin/node_modules/aws-sdk/scripts/services-table-generator.ts: No such file or directory
Target //:swc failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.758s, Critical Path: 0.27s
INFO: 8 processes: 6 internal, 2 local.
FAILED: Build did NOT complete successfully
```